default_stages: [pre-commit]
default_install_hook_types: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: make
        args: [mypy]
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
